### ISSUE TITLE
Address Field: Satellite vs. Streets Map Style

### ISSUE THREAD

**Issue by jakobhaerter** [doublesecretagency/craft-mapbox#3]
It's significantly more difficult to identify streets and cities with the current satellite view when using the map marker to generate an address. 

Is there a reason why the default [Streets Map Style](https://www.mapbox.com/maps/streets) isn't being used? The [Google Maps Plugin](https://plugins.doublesecretagency.com/google-maps/) uses a streets layer as well, which is perfect.

Thank you!

![image](https://github.com/doublesecretagency/craft-mapbox/assets/12596556/f53c3dc3-1f20-4590-9415-d7c34060544e)

**Comment by lindseydiloreto** [comment]
Hi @jakobhaerter, thanks for the suggestion! This has been changed in [v1.0.1](https://github.com/doublesecretagency/craft-mapbox/releases/tag/1.0.1). 👍 

I'm not sure there is a "default" per se, the style must always be specified when a map is created. But you're right, the `streets-v12` style does look much better than what we were using before.
